Add description for jsonb_build_array/object function
risingwavelabs/risingwave-docs-legacy pull request #1515
Opened 2023-11-14 07:29 UTC by WanYixian

## Info

- **Description**

  Add description for **jsonb_build_array** and **jsonb_build_object** function

- **Related code PR**

  https://github.com/risingwavelabs/risingwave/pull/13198

- **Related doc issue**
  
  Resolves https://github.com/risingwavelabs/risingwave-docs/issues/1479

## For reviewers

- **Preview**

  - [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **dev** version of the documentation. ]

- **Key points**

  - [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

2023-11-14 07:45 UTC, wangrunji0408 approved these changes
LGTM!

2023-11-14 08:03 UTC, CharlieSYH requested changes
Examples need to be updated. Rest LGTM.

2023-11-14 08:03 UTC, CharlieSYH commented on docs/sql/functions-operators/sql-function-json.md
> +```sql title=Example
We usually provide actual SQL statements for examples.

In this case:

```sql title=Example
SELECT jsonb_build_array(1, 2, 'foo', 4, 5);
------RESULT
 [1, 2, "foo", 4, 5]
 ```

2023-11-14 08:03 UTC, CharlieSYH commented on docs/sql/functions-operators/sql-function-json.md
> +```sql title=Example
This is what I got when I tested the example:

<img width="436" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/100549427/5e7f467a-7882-46c3-9dfa-8e708aeb20bc">

 {"2": {"f1": 3, "f2": "bar"}, "foo": 1}

2023-11-14 10:15 UTC, wangrunji0408 commented on docs/sql/functions-operators/sql-function-json.md
> +```sql title=Example
Thanks for pointing this out. The actual output is different from pg example because we are using `jsonb` type, while in the example it is `json`. The `json` type keeps the original order, but the `jsonb` type normalizes the data, so the output json object is sorted by key.

2023-11-16 05:51 UTC, wangrunji0408 approved these changes

2023-11-17 09:01 UTC, CharlieSYH approved these changes
LGTM

2023-11-17 09:05 UTC, merged