1702 document feat introduce alter parallelism
risingwavelabs/risingwave-docs-legacy pull request #1748
Opened 2024-01-10 09:53 UTC by ShanlanLi

## Info

- **Description**

  - [add set parallelism clause to alter table/sink/mv]
  - [restructure the [Key concepts and terms](https://docs.risingwave.com/docs/current/key-concepts/) ]
  - <img width="924" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/150168166/d11295cb-167b-4c3c-bdae-e19124c2938c">
  - Because the old method of categorizing terms made it difficult to find appropriate placements for new terms, we have now reorganized the classification of this page. The terms on this page are now divided into two main categories: one category is related to RisingWave, and the other category consists of more general terms. Within each category, the terms are sorted alphabetically by the first letter of each word.

- **Notes**

  - [ Include any sulementary context or references here. ]

- **Related code PR**

  - [ https://github.com/risingwavelabs/risingwave/pull/14240]

- **Related doc issue**
  
  Resolves [ https://github.com/risingwavelabs/risingwave-docs/issues/1702]

## For reviewers

- **Preview**

  - [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **dev** version of the documentation. ]

- **Key points**

  - [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

2024-01-12 03:34 UTC, CharlieSYH requested changes

2024-01-12 03:34 UTC, CharlieSYH commented on docs/concepts/key-concepts.md
> +This page explains key concepts and terms that are used throughout the documentation. It is divided into two parts. In the first part, we present some terms strongly related to RisingWave. In the sec
```suggestion
This page explains key concepts and terms that are used throughout the documentation. In the first part, we present terms closely related to RisingWave. In the second part, we include a broader range of terms in a glossary. 
```

2024-01-12 03:34 UTC, CharlieSYH commented on docs/concepts/key-concepts.md
> +Indexes in a database are typically created on one or more columns of a table, allowing the database management system (DBMS) to  locate and retrieve the desired data from the table quickly. This can
```suggestion
Indexes in a database are typically created on one or more columns of a table, allowing the database management system (DBMS) to locate and retrieve the desired data from the table quickly. This can significantly improve the performance of database queries, especially for large tables or frequently accessed tables. In RisingWave, indexes can speed up batch queries.
```

2024-01-12 03:34 UTC, CharlieSYH commented on docs/concepts/key-concepts.md
> +Parallelism refers to the technique of simultaneously executing multiple database operations or queries to improve performance and increase efficiency. It involves dividing a database workload into s
```suggestion
Parallelism refers to the technique of simultaneously executing multiple database operations or queries to improve performance and increase efficiency. It involves dividing a database workload into smaller tasks and executing them concurrently on multiple processors or machines. In RisingWave, you can set the parallelism of streaming jobs, like [tables](/sql/commands/sql-alter-table.md#set-parallelism), [materialized views](/sql/commands/sql-alter-materialized-view.md#set-parallelism), and [sinks](/sql/commands/sql-alter-sink.md#set-parallelism).
```

2024-01-12 03:34 UTC, CharlieSYH commented on docs/sql/commands/sql-alter-materialized-view.md
> +|**SET PARALLELISM**| This clause controls the degree of [parallelism](../../concepts/key-concepts.md#parallelism) for the targeted [streaming job](../../concepts/key-concepts.md#streaming-jobs).|
```suggestion
|**SET PARALLELISM**| This clause controls the degree of [parallelism](/concepts/key-concepts.md#parallelism) for the targeted [streaming job](/concepts/key-concepts.md#streaming-jobs).|
```

2024-01-12 03:34 UTC, CharlieSYH commented on docs/sql/commands/sql-alter-sink.md
> +|**SET PARALLELISM**| This clause controls the degree of [parallelism](../../concepts/key-concepts.md#parallelism) for the targeted [streaming job](../../concepts/key-concepts.md#streaming-jobs).|
```suggestion
|**SET PARALLELISM**| This clause controls the degree of [parallelism](/concepts/key-concepts.md#parallelism) for the targeted [streaming job](/concepts/key-concepts.md#streaming-jobs).|
```

2024-01-12 03:34 UTC, CharlieSYH commented on docs/sql/commands/sql-alter-table.md
> +| Parameters or clauses | Description                                                                                |
For table headings, we should use singular forms because the heading shows the nature of each row of a column. And each row has only one parameter or clause.

2024-01-12 03:34 UTC, CharlieSYH commented on docs/sql/commands/sql-alter-table.md
> +```sql title=Examples
Why use plural? There's only one sql statement here.

2024-01-12 03:34 UTC, CharlieSYH commented on docs/sql/commands/sql-alter-table.md
> +|**SET PARALLELISM**| This clause controls the degree of [parallelism](../../concepts/key-concepts.md#parallelism) for the targeted [streaming job](../../concepts/key-concepts.md#streaming-jobs).|
```suggestion
|**SET PARALLELISM**| This clause controls the degree of [parallelism](/concepts/key-concepts.md#parallelism) for the targeted [streaming job](/concepts/key-concepts.md#streaming-jobs).|
```

2024-01-12 03:34 UTC, CharlieSYH commented on docs/sql/commands/sql-alter-table.md
> +| *parallelism_number* | This parameter can be `AUTO` or a fixed number, like 1, 2, 3, etc. Altering the parameter to `AUTO` will expand the streaming job's degree of parallelism to encompass all ava
```suggestion
| *parallelism_number* | This parameter can be `AUTO` or a fixed number, like 1, 2, 3, etc. Altering the parameter to `AUTO` will expand the streaming job's degree of parallelism to encompass all available units, whereas setting it to a fixed number will lock the job's parallelism at that specific figure. Setting it to `0` is equivalent to `AUTO`. <br/><br/>After setting the parallelism, the parallelism status of a table can be observed within the internal [`rw_table_fragments`](/manage/view-configure-runtime-parameters.md) table or the [`rw_fragments`](/manage/view-configure-runtime-parameters.md)table.|
```

2024-01-12 03:34 UTC, CharlieSYH commented on docs/sql/commands/sql-alter-table.md
> +First, let's set the parallelism to `3` by the [`SET` command](../../manage/view-configure-runtime-parameters.md#how-to-configure-runtime-parameters).
```suggestion
First, let's set the parallelism to `3` by the [`SET` command](/manage/view-configure-runtime-parameters.md#how-to-configure-runtime-parameters).
```

2024-01-12 03:34 UTC, CharlieSYH commented on docs/sql/commands/sql-alter-table.md
> +Then let's create a table to view the parallelism we set. As mentioned, the parallelism status of a table can be observed within the [`rw_fragments`](../../manage/view-configure-runtime-parameters.md
```suggestion
Then let's create a table to view the parallelism we set. As mentioned, the parallelism status of a table can be observed within the [`rw_fragments`](/manage/view-configure-runtime-parameters.md) table.
```

2024-01-12 03:34 UTC, CharlieSYH commented on docs/concepts/key-concepts.md
> +Parallelism refers to the technique of simultaneously executing multiple database operations or queries to improve performance and increase efficiency. It involves dividing a database workload into s
We use absolute paths (starting after `/docs`), not relative paths, in our docs. See this page: https://www.notion.so/risingwave-labs/Tips-for-Markdown-Docusaurus-70bc8f0c686f4fdf82430eba1fd582fb?pvs=4#619b078bf36046b5aa04d3ecb381701b

2024-01-12 12:58 UTC, ShanlanLi commented on docs/concepts/key-concepts.md
> +A node is a logical collection of IT resources that handles specific workloads based on their types. There are two types of nodes in RisingWave:
@CharlieSYH  Could you pls check this concept? It lists 3 nodes but says it has two types of nodes. I'm a bit confused.

2024-01-15 03:53 UTC, WanYixian approved these changes
Rest LGTM

2024-01-15 03:53 UTC, WanYixian commented on docs/concepts/key-concepts.md
> +A group of interconnected nodes and services that acts as a single system running an instance of RisingWave.
act, not acts

2024-01-15 03:53 UTC, WanYixian commented on docs/concepts/key-concepts.md
> +### Compactor nodes
Compact nodes

2024-01-15 03:53 UTC, WanYixian commented on docs/concepts/key-concepts.md
> +In RisingWave, When a streaming query plan executes, it divides into multiple independent fragments to allow parallel execution. Each fragment is a chain of SQL operators. Under the hood, it is execu
In RisingWave, **when** a streaming query plan executes (lower case)

2024-01-15 03:53 UTC, WanYixian commented on docs/concepts/key-concepts.md
> +- Compactor node
Compact node

2024-01-15 06:27 UTC, shanicky commented on docs/sql/commands/sql-alter-sink.md
> +ALTER SINK s set PARALLELISM = 4;
Should "set" be capitalized here?

2024-01-15 08:40 UTC, CharlieSYH approved these changes

2024-01-15 08:44 UTC, merged