Create pull_request_template.md
risingwavelabs/risingwave-docs-legacy pull request #177
Opened 2022-07-25 06:52 UTC by CharlieSYH

Add a PR template that includes a checklist and complete PR process.

2022-08-01 08:33 UTC, hengm3467 requested changes

2022-08-01 08:33 UTC, hengm3467 commented on .github/pull_request_template.md
> +  ***After merging this PR, paste the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/.***
@CharlieSYH Is it intended that the texts are in bold? 
Aside from that, I would suggest revising the last section to "After merging this PR, edit the description to include the links to the updated doc pages in this section. For example..."

2022-08-02 03:12 UTC, CharlieSYH commented on .github/pull_request_template.md
> +  ***After merging this PR, paste the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/.***
Yes, the text in ***bold & italic*** are placeholders that meant to be replaced by actual information. I made them conspicuous so that users are less likely to ignore them.

In addition, the text in the source code view is all bold but I don't know why (the highlighting for 'Write' might fail to recognize ***bold & italic***). You can switch to the preview to see the correct outcome.

2022-08-02 03:15 UTC, CharlieSYH commented on .github/pull_request_template.md
> +  ***After merging this PR, paste the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/.***
:
After merging this PR, edit the description to include the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/.

2022-08-02 03:33 UTC, hengm3467 approved these changes

2022-08-02 03:50 UTC, merged