Add issue templates (forms)
risingwavelabs/risingwave-docs-legacy pull request #178
Opened 2022-07-26 15:45 UTC by CharlieSYH

2022-08-01 05:06 UTC, hengm3467 requested changes

2022-08-01 05:06 UTC, hengm3467 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +description: Notice any typos, misused terms, inconsistencies, or ambiguities in the docs? Give us a little hint!
Notice -> Noticed
Give us a little hint! -> Let us know!

2022-08-01 05:06 UTC, hengm3467 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        What an astute observer! I guess no bugs can escape from your penetrating insight, huh? Thanks for making the docs better!
@CharlieSYH Can we say something that's plain and straightforward? :)

2022-08-01 05:36 UTC, CharlieSYH commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        What an astute observer! I guess no bugs can escape from your penetrating insight, huh? Thanks for making the docs better!
:
What an astute observer! Please describe the bug by filling out the form below. Thanks for making the docs better!

2022-08-02 04:57 UTC, hengm3467 approved these changes

2022-08-02 04:57 UTC, merged