Add concatenation function and operator
risingwavelabs/risingwave-docs-legacy pull request #184
Opened 2022-08-02 09:03 UTC by CharlieSYH

## Info
- **Description**: 
Added the CONCAT function and || operator.

- **Related code PR**: 
https://github.com/singularity-data/risingwave/pull/3091

Resolves #141 

## Before merging,
☑️ if true or not applicable:
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked related doc issue to this PR in **Development**. 
  - [ ] I have accquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview and the updated parts look all good. <details><summary>How?</summary><img width="852" alt="image" src="https://user-images.githubusercontent.com/100549427/180817529-5ab18ea5-f36b-4663-8002-a43d511be7ab.png"></details>
  - [ ] (For version-specific PR) I have confirmed that this PR is for a released version. If the software version is not released, put it on hold.

## Published doc pages
  [ After merging this PR, edit the description to include the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/. ]

2022-08-02 12:59 UTC, kwannoel approved these changes

2022-08-02 13:01 UTC, kwannoel requested changes
![2022-08-02-210028_823x196_scrot](https://user-images.githubusercontent.com/47273164/182380833-ea439b69-a731-4a7c-855b-e23f2a824ab8.png)

seems like it should not be escaped `\|\|`. Otherwise LGTM.

2022-08-04 10:24 UTC, CharlieSYH commented
> seems like it should not be escaped `\|\|`. Otherwise LGTM.

Problem solved:
<img width="723" alt="image" src="https://user-images.githubusercontent.com/100549427/182824137-ba14c9c8-9e12-4b06-87e5-ae0983583c88.png">

2022-08-04 10:25 UTC, kwannoel approved these changes

2022-08-11 21:48 UTC, emile-00 approved these changes

2022-08-15 14:51 UTC, merged