1811 feat add io threads and correspondence of data types for python udf
risingwavelabs/risingwave-docs-legacy pull request #1920
Opened 2024-03-05 07:58 UTC by ShanlanLi

## Info

- **Description**

  - [ As title.]

- **Notes**

  - [ ]

- **Related code PR**

  - [ Provide a link to the relevant code PR here, if applicable. ]

- **Related doc issue**
  
  Resolves https://github.com/risingwavelabs/risingwave-docs/issues/1811

## For reviewers

- **Preview**

  - [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **dev** version of the documentation. ]

- **Key points**

  - [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

2024-03-05 08:57 UTC, wangrunji0408 requested changes
We should clarify that `io_threads` is only useful for IO-intensive functions.
Rest LGTM, thank you!

2024-03-05 08:57 UTC, wangrunji0408 commented on docs/sql/udf/udf-python.md
>  def gcd(x, y):
`io_threads` is not designed for this kind of functions.

We can add another example to show the expected scenario:

```python
# set the `io_threads` parameter to run multiple function calls concurrently on a thread pool
@udf(input_types=["INT"], result_type="INT", io_threads=32)
def blocking(x):
    time.sleep(0.01) # some blocking operations
    return x
```

2024-03-05 08:57 UTC, wangrunji0408 commented on docs/sql/udf/udf-python.md
> +- The scalar function `gcd`, decorated with `@udf`, takes two integer inputs and returns the greatest common divisor of the two integers. The `io_threads` parameter specifies the number of threads th
```suggestion
- The scalar function `gcd`, decorated with `@udf`, takes two integer inputs and returns the greatest common divisor of the two integers. 
- The scalar function `blocking`, decorated with `@udf`. The `io_threads` parameter specifies the number of threads that the Python UDF will use during execution to enhance processing performance of IO-intensive functions. Please note that multithreading can not speed up compute-intensive functions due to the GIL.
```

2024-03-14 10:32 UTC, wangrunji0408 approved these changes

2024-03-15 07:44 UTC, CharlieSYH approved these changes

2024-03-15 07:48 UTC, merged