Sys Info Functions
risingwavelabs/risingwave-docs-legacy pull request #193
Opened 2022-08-09 01:04 UTC by bernscode

## Info
- **Description**: 
[ What's changed? ]

- **Related code PR**: 
[ Provide link to the code PR here. For example, https://github.com/singularity-data/risingwave/pull/4085. Delete this part if there's no code PR related. ]

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked related doc issue to this PR in **Development**.
  - [ ] I have accquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview and the updated parts look all good. <details><summary>How?</summary><img width="852" alt="image" src="https://user-images.githubusercontent.com/100549427/180817529-5ab18ea5-f36b-4663-8002-a43d511be7ab.png"></details>
  - [ ] (For version-specific PR) I have confirmed that this PR is for a released version. If the software version is not released, put it on hold.

## Published doc pages
  [ After merging this PR, edit the description to include the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/. ]

2022-08-09 01:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/singularity-data/risingwave-docs?pullRequest=193) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/singularity-data/risingwave-docs?pullRequest=193) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/singularity-data/risingwave-docs?pullRequest=193) it.</sub>

2022-08-10 03:27 UTC, hengm3467 approved these changes
LGTM

2022-08-15 08:17 UTC, hengm3467 commented on sidebars.js
> +            label: 'System Information',
@bernscode System Information - > System information (with "i" in lower case).

2022-08-15 14:41 UTC, CharlieSYH commented
Now that the standard names for data types are finalized, we can update and backfill the Data types page https://www.risingwave.dev/docs/latest/sql-data-types/. @bernscode 

             DataType::Boolean => f.write_str("boolean"),
             DataType::Int16 => f.write_str("smallint"),
             DataType::Int32 => f.write_str("integer"),
             DataType::Int64 => f.write_str("bigint"),
             DataType::Float32 => f.write_str("real"),
             DataType::Float64 => f.write_str("double precision"),
             DataType::Decimal => f.write_str("numeric"),
             DataType::Date => f.write_str("date"),
             DataType::Varchar => f.write_str("character varying"),
             DataType::Time => f.write_str("time without time zone"),
             DataType::Timestamp => f.write_str("timestamp without time zone"),
             DataType::Timestampz => f.write_str("timestamp with time zone"),
             DataType::Interval => f.write_str("interval"),
             DataType::Struct { .. } => f.write_str("record"),
             DataType::List { datatype } => write!(f, "{}[]", datatype),

2022-08-15 14:41 UTC, CharlieSYH requested changes

2022-08-15 14:41 UTC, CharlieSYH commented on docs/sql/functions-operators/sql-function-sys-info.md
> +| pg_typeof() → regtype |Returns the standard name of the data type of the provided value. <br /> More specifically, it returns the OID of the data type of the provided value. It returns a regtype, w
- We don't use complete statements in the examples for functions and operators. Therefore: `pg_typeof(round(null))` → `double precision`
- Could have more examples.

2022-08-15 14:46 UTC, CharlieSYH commented
Please set the Milestone for your other pull requests. I've selected the correct version for this PR:
<img width="330" alt="image" src="https://user-images.githubusercontent.com/100549427/184657402-028e8733-f563-4ce0-9864-8a228d4b7e98.png">
You can get the version in the corresponding doc issue.

2022-08-15 22:10 UTC, bernscode commented on sidebars.js
> +            label: 'System Information',
Updated and committed change. Thanks!

2022-08-15 22:11 UTC, bernscode commented on docs/sql/functions-operators/sql-function-sys-info.md
> +| pg_typeof() → regtype |Returns the standard name of the data type of the provided value. <br /> More specifically, it returns the OID of the data type of the provided value. It returns a regtype, w
Nice catch! I noticed this while working through other updates. Updated and committed change. Thanks!

2022-08-17 03:18 UTC, CharlieSYH approved these changes

2022-08-17 03:20 UTC, merged