Add string as an alias for data type varchar.
risingwavelabs/risingwave-docs-legacy pull request #195
Opened 2022-08-09 19:51 UTC by bernscode

Add string as an alias for data type varchar.

## Info
- **Description**: 
Add string as an alias for data type varchar.

- **Related code PR**: 
https://github.com/singularity-data/risingwave/pull/3094

- **Related doc issue**: 
https://github.com/singularity-data/risingwave-docs/issues/142

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked related doc issue to this PR in **Development**.
  - [ ] I have accquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview and the updated parts look all good. <details><summary>How?</summary><img width="852" alt="image" src="https://user-images.githubusercontent.com/100549427/180817529-5ab18ea5-f36b-4663-8002-a43d511be7ab.png"></details>
  - [ ] (For version-specific PR) I have confirmed that this PR is for a released version. If the software version is not released, put it on hold.

## Published doc pages
  [ After merging this PR, edit the description to include the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/. ]

2022-08-09 19:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/singularity-data/risingwave-docs?pullRequest=195) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/singularity-data/risingwave-docs?pullRequest=195) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/singularity-data/risingwave-docs?pullRequest=195) it.</sub>

2022-08-10 21:46 UTC, emile-00 approved these changes

2022-08-15 14:21 UTC, CharlieSYH requested changes

2022-08-15 14:21 UTC, CharlieSYH commented on docs/sql/sql-data-types.md
> +|character varying|string|Variable-length character string. We do not support specifying the maximum length as of now.|
Actually, the code change is about adding string as an alias to varchar. And varchar is an alias to character varying. See v1 and v8 in the e2e testing (both varchar and string are ok):
<img width="923" alt="image" src="https://user-images.githubusercontent.com/100549427/184652267-47a1ec33-c46d-4ef3-a494-5a7db1fd1ca6.png">

Therefore:
|character varying|varchar, string|Variable-length character string. We do not support specifying the maximum length as of now.|

2022-08-15 21:52 UTC, bernscode commented on docs/sql/sql-data-types.md
> +|character varying|string|Variable-length character string. We do not support specifying the maximum length as of now.|
Thanks for the clarification. I've added and committed the change. Thanks!

2022-08-16 07:34 UTC, CharlieSYH approved these changes
All good

2022-08-16 21:20 UTC, merged