Doc ignore_key for Debezium JSON AVRO
risingwavelabs/risingwave-docs-legacy pull request #1971
Opened 2024-03-18 21:19 UTC by emile-00

## Info

- **Description**

  - Doc `ignore_key` parameter for Debezium JSON and AVRO formats

- **Notes**

  - [ Include any supplementary context or references here. ]

- **Related code PR**

  - https://github.com/risingwavelabs/risingwave/pull/15304

- **Related doc issue**
  
  Resolves https://github.com/risingwavelabs/risingwave-docs/issues/1910

## For reviewers

- **Preview**

  - [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **dev** version of the documentation. ]

- **Key points**

  - [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`CharlieSYH`, `emile-00`, & `hengm3467`).

2024-03-19 07:30 UTC, ShanlanLi requested changes

2024-03-19 07:30 UTC, ShanlanLi commented on docs/ingest/supported-sources-and-formats.md
> +Optionally, you can define a `schema.registry.name.strategy` if `schema.registry` is set. Accepted options include `topic_name_strategy`, `record_name_strategy`, and `topic_record_name_strategy`. If
The sentence was not completed.

2024-03-19 07:34 UTC, ShanlanLi commented on docs/ingest/supported-sources-and-formats.md
> +Optionally, you can define a `schema.registry.name.strategy` if `schema.registry` is set. Accepted options include `topic_name_strategy`, `record_name_strategy`, and `topic_record_name_strategy`. If
and I suggest add some information to this link text:

2024-03-20 04:08 UTC, tabVersion approved these changes
LGTM

2024-03-20 04:17 UTC, WanYixian approved these changes

2024-03-20 05:47 UTC, ShanlanLi approved these changes
LGTM, thanks!

2024-03-20 20:16 UTC, merged