Support some date/time operations.
risingwavelabs/risingwave-docs-legacy pull request #209
Opened 2022-08-10 22:33 UTC by bernscode

Support some date/time operations.

## Info
- **Description**: 
Support some date/time operations:
date + int32
int32 + date
date - int32
date + time
time + date
time - time
time + interval
time - interval

- **Related code PR**: 
https://github.com/singularity-data/risingwave/pull/3472

- **Related doc issue**: 
Resolves https://github.com/singularity-data/risingwave-docs/issues/161

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked related doc issue to this PR in **Development**.
  - [ ] I have accquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview and the updated parts look all good. <details><summary>How?</summary><img width="852" alt="image" src="https://user-images.githubusercontent.com/100549427/180817529-5ab18ea5-f36b-4663-8002-a43d511be7ab.png"></details>
  - [ ] (For version-specific PR) I have confirmed that this PR is for a released version. If the software version is not released, put it on hold.

## Published doc pages
  [ After merging this PR, edit the description to include the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/. ]

2022-08-10 22:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/singularity-data/risingwave-docs?pullRequest=209) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/singularity-data/risingwave-docs?pullRequest=209) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/singularity-data/risingwave-docs?pullRequest=209) it.</sub>

2022-08-11 18:27 UTC, emile-00 approved these changes

2022-08-15 10:01 UTC, CharlieSYH approved these changes

2022-08-15 10:01 UTC, CharlieSYH commented on docs/sql/functions-operators/sql-function-datetime.md
> +| date + int → date | Add an int to a date. | `date '2022-06-23' + 4` → `2022-06-27` <br /> `4 + Date '2022-06-23'` → `2022-06-27` |
Maybe we should avoid abbreviations in the description: 
"Add an integer to a date."

2022-08-15 21:31 UTC, bernscode commented on docs/sql/functions-operators/sql-function-datetime.md
> +| date + int → date | Add an int to a date. | `date '2022-06-23' + 4` → `2022-06-27` <br /> `4 + Date '2022-06-23'` → `2022-06-27` |
Good point! I've added and committed the change. Thanks!

2022-08-16 08:08 UTC, hengm3467 commented on docs/sql/functions-operators/sql-function-datetime.md
> +| date - int → date | Subtract an int from a date. | `date '2022-06-23' - 4` → `2022-06-19` |
@bernscode Same comment as the one by Charlie. -> Subtract an integer from a date.

2022-08-16 08:14 UTC, hengm3467 requested changes

2022-08-16 08:14 UTC, hengm3467 commented on docs/sql/functions-operators/sql-function-datetime.md
> +| date + int → date | Add an integer to a date. | `date '2022-06-23' + 4` → `2022-06-27` <br /> `4 + Date '2022-06-23'` → `2022-06-27` |
This isn't clear. How about this: Add a number of days to a date.

2022-08-16 08:14 UTC, hengm3467 commented on docs/sql/functions-operators/sql-function-datetime.md
> +| date - int → date | Subtract an int from a date. | `date '2022-06-23' - 4` → `2022-06-19` |
Same here. -- > Subtract a number of days from a date.

2022-08-16 08:14 UTC, hengm3467 commented on docs/sql/functions-operators/sql-function-datetime.md
> +| date + time → timestamp | Add time to a date. | `date '2022-06-23' + time '19:24:00'` → `2022-06-23 19:24:00` <br /> `time '19:24:00' +  date '2022-06-23'` → `2022-06-23 19:24:00` |
--> Add a time to a date.

2022-08-16 08:14 UTC, hengm3467 commented on docs/sql/functions-operators/sql-function-datetime.md
> +| time - time → time | Subtract time from time. | `time '18:20:49' -  time '16:07:16'` → `02:13:33` |
--> Subtract a time from a time;
(Or) Subtract times.

2022-08-16 08:14 UTC, hengm3467 commented on docs/sql/functions-operators/sql-function-datetime.md
> +| time + interval → time | Add an interval to time. | `time '18:20:49' +  interval '1 hour'` → `19:20:49` |
-> "Add an interval to a time."

2022-08-16 08:14 UTC, hengm3467 commented on docs/sql/functions-operators/sql-function-datetime.md
> +| time - interval → time | Subtract an interval from time. | `time '18:20:49' -  interval '2 hours'` → `16:20:49` |
-> "Subtract an interval from a time."

2022-08-16 21:30 UTC, bernscode commented on docs/sql/functions-operators/sql-function-datetime.md
> +| date + int → date | Add an integer to a date. | `date '2022-06-23' + 4` → `2022-06-27` <br /> `4 + Date '2022-06-23'` → `2022-06-27` |
Good point! I agree, that does provide more clarity. I've updated this change. Thanks!

2022-08-16 21:31 UTC, bernscode commented on docs/sql/functions-operators/sql-function-datetime.md
> +| date - int → date | Subtract an int from a date. | `date '2022-06-23' - 4` → `2022-06-19` |
Updated change. Thanks!

2022-08-16 21:32 UTC, bernscode commented on docs/sql/functions-operators/sql-function-datetime.md
> +| date + time → timestamp | Add time to a date. | `date '2022-06-23' + time '19:24:00'` → `2022-06-23 19:24:00` <br /> `time '19:24:00' +  date '2022-06-23'` → `2022-06-23 19:24:00` |
Sounds good. Updated change. Thanks!

2022-08-16 21:35 UTC, bernscode commented on docs/sql/functions-operators/sql-function-datetime.md
> +| time - time → time | Subtract time from time. | `time '18:20:49' -  time '16:07:16'` → `02:13:33` |
I think the former recommendation (Subtract a time from a time) works best here. Updated change. Thanks!

2022-08-16 21:36 UTC, bernscode commented on docs/sql/functions-operators/sql-function-datetime.md
> +| time + interval → time | Add an interval to time. | `time '18:20:49' +  interval '1 hour'` → `19:20:49` |
Updated change. Thanks!

2022-08-17 02:06 UTC, hengm3467 approved these changes
LGTM

2022-08-17 02:08 UTC, merged