Add doc of DynamoDB sink
risingwavelabs/risingwave-docs-legacy pull request #2299
Opened 2024-06-24 04:34 UTC by WanYixian

## Info

- **Description**

  - Add doc of DynamoDB sink

- **Related code PR**

  - https://github.com/risingwavelabs/risingwave/pull/16670

- **Related doc issue**
  
  Resolves https://github.com/risingwavelabs/risingwave-docs/issues/2228

## For reviewers

- **Preview**

  - [ Paste the preview link to the updated page(s) here. Edit this item after the preview site is ready. To find the updated pages, scroll down to locate and open the Amplify preview link and select the **dev** version of the documentation. ]

- **Key points**

  - [ Parts that may need revision or extra consideration. ]

## Before merging

- [ ] I have checked the doc site preview, and the updated parts look good.

- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`emile-00`, `hengm3467`, & `WanYixian`).

2024-06-25 22:50 UTC, emile-00 commented on docs/guides/sink-to-dynamodb.md
> +For the DynamoDB sink to function correctly, it is required that the source table in RisingWave has a composite primary key comprising two columns, each corresponding to the partition key and sort ke
```suggestion
For the DynamoDB sink to function correctly, it is required that the source table in RisingWave has a composite primary key comprising two columns, corresponding to the partition key and sort key defined in the target DynamoDB table.
```

2024-06-25 22:51 UTC, emile-00 approved these changes

2024-06-26 05:29 UTC, ShanlanLi approved these changes
LGTM

2024-06-26 07:01 UTC, jetjinser requested changes
LGTM!

2024-06-26 07:01 UTC, jetjinser commented on docs/guides/sink-to-dynamodb.md
> +| character varying (varchar) | string (S)         |
```suggestion
| double precision            | number (N)         |
| serial                      | number (N)         |
| character varying (varchar) | string (S)         |
```

2024-06-26 07:03 UTC, jetjinser approved these changes

2024-06-26 07:17 UTC, merged