Added "Server..." tutorial
risingwavelabs/risingwave-docs-legacy pull request #235
Opened 2022-08-23 01:56 UTC by emile-00

## Info
- **Description**: 
Added the "Server performance anomaly detection" to the tutorial section. 

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview and the updated parts look all good. <details><summary>How?</summary><img width="852" alt="image" src="https://user-images.githubusercontent.com/100549427/180817529-5ab18ea5-f36b-4663-8002-a43d511be7ab.png"></details>
  - [ ] (For version-specific PR) I have confirmed that this PR is for a released version. If the software version is not released, put it on hold.

## Published doc pages
  [ After merging this PR, edit the description to include the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/. ]

2022-08-23 02:04 UTC, hengm3467 commented
@emile-00  Please help update the title of the other tutorial from "Perform real-time ad performance analysis" to "Real-time ad performance analysis", so that it's consistent with the new tutorial

2022-08-23 02:53 UTC, CharlieSYH requested changes

2022-08-23 02:53 UTC, CharlieSYH commented on docs/tutorials/server-performance-anomaly-detection.md
> +Please refer to this [guide](https://www.risingwave.dev/docs/latest/sql-function-time-window/) for an explanation of the tumble function and aggregations.
We should use the file path instead as the domain name 'www.risingwave.dev' could change in the future.
Revision: [guide](/sql/functions-operators/sql-function-time-window.md)

2022-08-24 02:45 UTC, hengm3467 approved these changes
Looks good!

2022-08-24 02:49 UTC, CharlieSYH approved these changes
Looks great!

2022-08-24 02:51 UTC, merged