IN expression support for null.
risingwavelabs/risingwave-docs-legacy pull request #241
Opened 2022-08-25 19:03 UTC by bernscode

IN expression support for null.

## Info
- **Description**: 
IN expression now supports null values.

- **Related code PR**: 
https://github.com/singularity-data/risingwave/pull/3974

- **Related doc issue**: 
Resolves https://github.com/singularity-data/risingwave-docs/issues/215

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview and the updated parts look all good. <details><summary>How?</summary><img width="852" alt="image" src="https://user-images.githubusercontent.com/100549427/180817529-5ab18ea5-f36b-4663-8002-a43d511be7ab.png"></details>
  - [ ] (For version-specific PR) I have confirmed that this PR is for a released version. If the software version is not released, put it on hold.

## Published doc pages
  [ After merging this PR, edit the description to include the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/. ]

2022-09-01 05:31 UTC, CharlieSYH requested changes

2022-09-01 05:31 UTC, CharlieSYH commented on docs/sql/functions-operators/sql-function-comparison.md
> +| IN() | `operand IN (value,...)` <br /> Whether a value is equal to any of the values you specify. <br /> TRUE if the operand is equal to one of the specified expressions/values. NULL if the operand
For this example `99 IN (null, 3, 2, min(v1)) → NULL`, it's better to remove min(v1) because the result could be 99. In this case, it will return true, not null. 
But the previous example doesn't have this problem since the first operand is null and the result will always be null.

2022-09-01 22:39 UTC, bernscode commented on docs/sql/functions-operators/sql-function-comparison.md
> +| IN() | `operand IN (value,...)` <br /> Whether a value is equal to any of the values you specify. <br /> TRUE if the operand is equal to one of the specified expressions/values. NULL if the operand
@CharlieSYH Excellent point! I've made the recommended change. Let me know if there's anything else that can be improved. Thanks!

2022-09-05 04:31 UTC, CharlieSYH approved these changes

2022-09-05 05:12 UTC, hengm3467 approved these changes
LGTM

2022-09-09 02:27 UTC, merged