fix: make sure the reference link in create index doc is correct
risingwavelabs/risingwave-docs-legacy pull request #2631
Opened 2024-09-23 08:50 UTC by hzxa21

## Description

The previous link won't work in the create index doc. This PR fixes it.

## Related code PR

## Related doc issue

Resolve

## Rendered preview

## Checklist

- [ ] I have checked the doc site preview, and the updated parts look good.
- [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`emile-00`, `hengm3467`, & `WanYixian`).

2024-09-23 08:54 UTC, st1page approved these changes

2024-09-24 02:58 UTC, stdrc requested changes

2024-09-24 02:58 UTC, stdrc commented on docs/sql/commands/sql-create-index.md
> +|**DISTRIBUTED BY** clause|Specify the index distribution key.<ul><li>As a distributed database, RisingWave distributes the data across multiple nodes. When an index is created, the distribution key
```suggestion
|**INCLUDE** clause|Specify the columns to include in the index as non-key columns.<ul><li>An index-only query can return the values of non-key columns without having to visit the indexed table thus improving the performance.</li><li>If you omit the `INCLUDE` clause, all columns of the table or materialized view will be indexed. This is recommended in RisingWave.</li><li>If you only want to include the `index_column`, use `CREATE INDEX ON object_name(index_column) INCLUDE(index_column);`.</li><li>See [How to decide which columns to include](../../transform/indexes.md#how-to-decide-which-columns-to-include) for more information.</li></ul>|
|**DISTRIBUTED BY** clause|Specify the index distribution key.<ul><li>As a distributed database, RisingWave distributes the data across multiple nodes. When an index is created, the distribution key is used to determine how the data should be distributed across these nodes.</li><li>If you omit the `DISTRIBUTED BY` clause, the first index column will be be used as the default distribution key.</li><li>`distributed_column` has to be the prefix of `index_column`.</li><li>See [How to decide the index distribution key](../../transform/indexes.md#how-to-decide-the-index-distribution-key) for more information.</li></ul>|
```

2024-09-24 03:05 UTC, hengm3467 approved these changes

2024-09-25 04:25 UTC, stdrc approved these changes

2024-09-25 04:26 UTC, merged