Add support for lowercase in to_char function
risingwavelabs/risingwave-docs-legacy pull request #297
Opened 2022-10-05 23:22 UTC by bernscode

Add support for lowercase in to_char function. I was not able to find other similar functions for function formatting or that use the formatting characters of to_char().

## Info
- **Description**: 
Add support for lowercase in to_char function. I was not able to find other similar functions for function formatting or that use the formatting characters of to_char().

- **Related code PR**: 
https://github.com/risingwavelabs/risingwave/pull/5032

- **Related doc issue**: 
Resolves https://github.com/risingwavelabs/risingwave-docs/issues/295

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary><img width="852" alt="image" src="https://user-images.githubusercontent.com/100549427/180817529-5ab18ea5-f36b-4663-8002-a43d511be7ab.png"></details>

## Published doc pages
  [ After merging this PR, edit the description to include the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/. ]

2022-10-06 01:35 UTC, TennyZhuang approved these changes

2022-10-09 08:01 UTC, hengm3467 requested changes
Generally looks good to me. The only comment is about using third-person singular verbs to start the description part. Please do a global search in the file and apply this recommendation. Thanks! 
I'll add this practice/recommendation into our style guide.

2022-10-13 21:19 UTC, bernscode commented
@hengm3467 Good point! I've made a new commit updating the third-person singular verbs on date/time and array page. Thanks!

2022-10-20 02:30 UTC, hengm3467 approved these changes
LGTM

2022-10-20 02:31 UTC, merged