Support for UNION and UNION ALL operators
risingwavelabs/risingwave-docs-legacy pull request #408
Opened 2022-11-30 23:24 UTC by bernscode

Support for UNION and UNION ALL operators.

## Info
- **Description**: 
Support for UNION and UNION ALL operators.

- **Related code PR**: 
https://github.com/risingwavelabs/risingwave/pull/6397 and https://github.com/risingwavelabs/risingwave/pull/6363

- **Related doc issue**: 
Resolves https://github.com/risingwavelabs/risingwave-docs/issues/375

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: <img width="916" alt="image" src="https://user-images.githubusercontent.com/100549427/199641563-82967cd0-2c5c-4f40-bcdb-5ac80f03ffd8.png">
</details>

## Published doc pages
  [ After merging this PR, edit the description to include the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/. ]

2022-12-01 02:53 UTC, chenzl25 commented
https://github.com/risingwavelabs/risingwave/pull/6425

2022-12-01 02:58 UTC, chenzl25 requested changes

2022-12-01 02:58 UTC, chenzl25 commented on docs/sql/functions-operators/sql-function-set.md
> +
We also support `UNION` for streaming queries now.

2022-12-01 03:08 UTC, chenzl25 approved these changes
LGTM, thanks!

2022-12-01 03:09 UTC, bernscode commented on docs/sql/functions-operators/sql-function-set.md
> +
@chenzl25 Thanks for the update! I've updated the note on the latest commit.

2022-12-02 06:41 UTC, hengm3467 commented on docs/sql/functions-operators/sql-function-set.md
> +Suppose that we have a table, "points_scored_current_week", that consists of these columns: `id`, `first_half`, and `second_half`.
@bernscode Please use code style for table names. Reer to the <i>Quick reference for user documentation</i> topic in our Style Guide for details.

2022-12-02 06:41 UTC, hengm3467 commented on docs/sql/functions-operators/sql-function-set.md
> +Next, suppose that we have a second table, "points_scored_last_week", that consists of these columns: `id`, `first_half`, and `second_half`.
Same here. Code style for table names. @bernscode

2022-12-02 06:43 UTC, hengm3467 commented on docs/sql/functions-operators/sql-function-set.md
> +Next, suppose that we have a second table, "points_scored_last_week", that consists of these columns: `id`, `first_half`, and `second_half`.
@bernscode The rest looks good to me. Please resolve the comments and then you can merge this PR. Thanks!

2022-12-02 22:00 UTC, bernscode commented on docs/sql/functions-operators/sql-function-set.md
> +Suppose that we have a table, "points_scored_current_week", that consists of these columns: `id`, `first_half`, and `second_half`.
@hengm3467 Thanks for the feedback! I actually followed the styling from the table names on the [Time window functions](https://www.risingwave.dev/docs/latest/sql-function-time-window/) page (Suppose that we have a table, "taxi_trips", that consists of these columns: `id`, `taxi_id`, `completed_at`, and `distance`.) However, I do see this styling noted in the Quick reference. I've made the update to the latest commit.

2022-12-02 22:01 UTC, bernscode commented on docs/sql/functions-operators/sql-function-set.md
> +Next, suppose that we have a second table, "points_scored_last_week", that consists of these columns: `id`, `first_half`, and `second_half`.
@hengm3467 Thanks! I've made the update on the latest commit. I'll resolve the comments and merge this PR.

2022-12-02 22:02 UTC, merged