Document the MySQL CDC support
risingwavelabs/risingwave-docs-legacy pull request #468
Opened 2022-12-27 03:33 UTC by hengm3467

## Info
- **Description**: 
Create a guide to describe the two approaches to ingest MySQL CDC data: the new MySQL CDC connector, and the old connector (Kafka + Debezium). Note that this is the initial guide, and more details will be added by Emily after verifying some of the details. 

- **Related code PR**: 
[ Provide the link to the code PR here. For example, https://github.com/risingwavelabs/risingwave/pull/4085. Delete this part if there's no code PR related. ]

- **Related doc issue**: 
Resolves #452 

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: <img width="916" alt="image" src="https://user-images.githubusercontent.com/100549427/199641563-82967cd0-2c5c-4f40-bcdb-5ac80f03ffd8.png">
</details>

## Published doc pages
  [ After merging this PR, edit the description to include the links to the updated doc pages here. For example, https://www.risingwave.dev/docs/latest/intro/. ]

2022-12-27 06:07 UTC, liurenjie1024 commented on docs/guides/ingest-from-mysql-cdc.md
> +MySQL has a binary log (binlog) that records all operations in the order in which they are committed to the database. This includes changes to table schemas as well as changes to the data in tables.
Remove this paragraph? I think this is about implementation details and we should not expose it to user.

2022-12-27 06:07 UTC, liurenjie1024 commented on docs/guides/ingest-from-mysql-cdc.md
> +RisingWave supports ingesting row-level data (`INSERT`, `UPDATE`, and `DELETE` operations) from the binlog of a MySQL database.
```suggestion
RisingWave supports ingesting row-level data (`INSERT`, `UPDATE`, and `DELETE` operations) from the changes of a MySQL database.
```

2022-12-27 06:07 UTC, liurenjie1024 commented on docs/guides/ingest-from-mysql-cdc.md
> +ROW FORMAT { DEBEZIUM_JSON | MAXWELL };
We don't need this line? cc @StrikeW

2022-12-27 06:07 UTC, liurenjie1024 commented on docs/guides/ingest-from-mysql-cdc.md
> +ROW FORMAT { DEBEZIUM_JSON | MAXWELL };
If this is for debezium, the row format should be debezium_json only and we should exclude maxwell.

2022-12-27 06:27 UTC, hengm3467 commented on docs/guides/ingest-from-mysql-cdc.md
> +ROW FORMAT { DEBEZIUM_JSON | MAXWELL };
@liurenjie1024 This is for the old CDC connector, which we support both Debezium JSON and Maxwell JSON. Maybe it's not accurate to say this approach is 'Debezium connector for MySQL'. I just changed it to be 'Debezium and Kafka' to be clearer.

@StrikeW Please double-confirm if Maxwell is supported in either of the approaches. Thanks!

2022-12-27 07:08 UTC, StrikeW commented on docs/guides/ingest-from-mysql-cdc.md
> +ROW FORMAT { DEBEZIUM_JSON | MAXWELL };
Currently, users need to specify row format explicitly, which is enforced by the CREATE SOURCE syntax. I think in future we can remove it for native CDC sources which can only be `debezium_json` format.  cc @neverchanje

2022-12-27 07:09 UTC, StrikeW commented on docs/guides/ingest-from-mysql-cdc.md
> +   connector='cdc',
Here should be `mysql-cdc` for MySQL and `postgres-cdc` for Postgres

2022-12-27 08:13 UTC, StrikeW commented on docs/guides/ingest-from-mysql-cdc.md
> +|database.port| Port number of the database.|
Syntax of these properties have been updated (e.g. `database.hostname` -> `hostname`). Please refer to this PR: https://github.com/risingwavelabs/risingwave/pull/6869

2022-12-28 09:32 UTC, CharlieSYH approved these changes

2022-12-28 09:32 UTC, CharlieSYH commented on docs/guides/ingest-from-mysql-cdc.md
> +::: note
Remove the empty space.
::: note -> :::note

2022-12-28 09:32 UTC, CharlieSYH commented on docs/guides/ingest-from-mysql-cdc.md
> +The supported MySQL version are 5.7 and 8.0.x.
The supported MySQL _version_ are  -> versions

2022-12-28 09:32 UTC, CharlieSYH commented on docs/guides/ingest-from-mysql-cdc.md
> +  You can use the [Debezium connector for MySQL](https://debezium.io/documentation/reference/stable/connectors/mysql.html) to convert MySQL data change streams to Kafka topics, and then use the Kafka
Us this approach is Kafka -> 
Use this approach if Kafka

2022-12-28 09:43 UTC, StrikeW commented on docs/guides/ingest-from-mysql-cdc.md
> +ROW FORMAT { DEBEZIUM_JSON | MAXWELL };
I think Maxwell only supports in the kafka cdc approach. You can confirm it with @tabVersion

2022-12-29 10:22 UTC, hengm3467 commented
Since the connector node is not ready for being made public, I'm converting this PR to draft and pick up the work later.

2023-01-02 16:48 UTC, tabVersion commented on docs/guides/ingest-from-mysql-cdc.md
> +ROW FORMAT { DEBEZIUM_JSON | MAXWELL };
> I think Maxwell only supports in the kafka cdc approach. You can confirm it with @tabVersion 

Yes, maxwell is supported in this way. 
Kafka can carry the bytes and debezium_json/maxwell parser will parse them into stream chunk.
CDC node embeds debezium engine within it and it is another pathway.

2023-01-12 07:53 UTC, neverchanje commented on docs/guides/ingest-from-mysql-cdc.md
> +The supported MySQL versions are 5.7 and 8.0.x.
Please confirm that. @StrikeW  AFAIK we can support versions 5.6, 5.7, 8.0., which are claimed by FlinkCDC.

2023-01-12 07:57 UTC, neverchanje commented on docs/guides/ingest-from-mysql-cdc.md
> +Before using the native MySQL CDC connector in RisingWave, you need to complete several configurations on MySQL. For details, see [Setting up MySQL](https://debezium.io/documentation/reference/stable
We need to maintain this part of the doc ourselves. It's Ok for now.

2023-01-12 08:02 UTC, neverchanje commented on docs/guides/ingest-from-mysql-cdc.md
> +The native MySQL CDC connector is implemented by a connector node. A connector node handles the connections with upstream and downstream systems, and it is currently only available in RiseDev, the de
> it is currently only available in RiseDev, the developer tool of RisingWave. 

There are two installation ways to have connector-node bundled. 1/ Installing using risedev, which is only recommended for developing purposes. 2/ Installing using Docker Compose. The lastest [risingwave-demo](https://github.com/risingwavelabs/risingwave-demo/tree/main/docker) has integrated the connector-node by default.

2023-01-12 08:03 UTC, neverchanje approved these changes
Rest LGTM

2023-01-16 08:18 UTC, tabVersion commented on docs/guides/ingest-from-mysql-cdc.md
> +The supported MySQL versions are 5.7 and 8.0.x.
since we are using debezium engine inside, the tested versions are: MySQL 5.7, 8.0.x
ref https://debezium.io/releases/

2023-02-06 08:48 UTC, CharlieSYH requested changes

2023-02-06 08:48 UTC, CharlieSYH commented on docs/guides/ingest-from-mysql-cdc.md
> +<Tabs>
Adding the following code before the first `<Tabs>` (if there're more), or the tabs will not be rendered properly.
```
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
```

2023-02-06 08:51 UTC, CharlieSYH commented on docs/guides/ingest-from-postgres-cdc.md
> +The supported PostgreSQL versions are 10, 11, 12, 13, and 14.
Just to be sure, is the latest PostgreSQL 15 supported?

2023-02-06 08:55 UTC, CharlieSYH commented on docs/guides/ingest-from-postgres-cdc.md
> +    shipment_id INTEGER,
We agreed to use lowercase for data types like integer and string.

2023-02-06 08:55 UTC, CharlieSYH commented on docs/guides/ingest-from-postgres-cdc.md
> +) with (
with ( 
->
WITH (

2023-02-06 09:03 UTC, CharlieSYH commented on docs/guides/ingest-from-mysql-cdc.md
> + You need to configure MySQL and run Maxwell's daemon to convert data changes to Kafka topics. For details, see the [Quick Start](https://maxwells-daemon.io/quickstart/) from Maxwell's Daemon.
from Maxwell's Daemon.
 ->
 from Maxwell's daemon.

2023-02-06 09:05 UTC, CharlieSYH commented on docs/guides/ingest-from-mysql-cdc.md
> +4. Modify your RDS instance and apply the modified paramter group to your database.
paramter group
->
parameter group

2023-02-06 09:10 UTC, CharlieSYH commented on docs/guides/ingest-from-mysql-cdc.md
> +|database.name| Name of the database. Note that RisingWave can not read data from a built-in MySQL database, such as `mysql`.|
can not
->
cannot

2023-02-06 09:18 UTC, CharlieSYH commented on docs/guides/ingest-from-postgres-cdc.md
> +- `Replication` privileges in the database to add the table to a publication.
`Replication` in all caps?

2023-02-06 09:20 UTC, CharlieSYH commented on docs/guides/ingest-from-postgres-cdc.md
> +- `CREATE` privileges on the database to add publications.
```- `CREATEDB` privileges ```?

2023-02-06 09:24 UTC, CharlieSYH commented on docs/guides/ingest-from-postgres-cdc.md
> + |hostname| Host name of the database. |
Hostname, not _Host name_
according to Google's SG.

2023-02-06 09:25 UTC, CharlieSYH commented on docs/guides/ingest-from-mysql-cdc.md
> +|hostname| Host name of the database. |
Hostname, not _Host name_

2023-02-06 09:25 UTC, CharlieSYH commented on docs/guides/ingest-from-mysql-cdc.md
> +|username| User name of the database.|
Username, not _User name_
according to Google's SG.

2023-02-06 09:26 UTC, CharlieSYH commented on docs/guides/ingest-from-postgres-cdc.md
> + |username| User name of the database.|
Username, not _User name_

2023-02-06 09:28 UTC, CharlieSYH commented on docs/guides/ingest-from-postgres-cdc.md
> + To ensure all data changes are captured, you must create a materialized source connection (`CREATE TABLE`) and specify primary keys. The data format must be Debezium JSON. For details
The last sentence seems not complete.
"For details"

2023-02-07 08:25 UTC, StrikeW commented on docs/guides/ingest-from-postgres-cdc.md
> +The supported PostgreSQL versions are 10, 11, 12, 13, and 14.
Not yet. It is supported by the newer version of Debezium, but we use an old version. We can upgrade to the new version in future release.

2023-02-07 08:25 UTC, StrikeW commented on docs/guides/ingest-from-mysql-cdc.md
> +### Create a materialized source using the native CDC connector in RisingWave
shall we change `materialized source` to `table`? These two concepts have been unified.

2023-02-07 08:25 UTC, StrikeW commented on docs/guides/ingest-from-mysql-cdc.md
> +See [Setting up MySQL](https://debezium.io/documentation/reference/stable/connectors/mysql.html#setting-up-mysql) and follow the steps on creating a user, granting the user required permissions, and
Shall we add the instructions to the doc directly and leave the link for further reference? I refined the draft on Notion a bit (Creating a user & Enabling the binlog).

2023-02-07 08:25 UTC, StrikeW commented on docs/guides/ingest-from-mysql-cdc.md
> +- Using RiseDev, the developer's tool
Here should have a line break, but it is not show in the preview version.

2023-02-07 08:25 UTC, StrikeW commented on docs/guides/ingest-from-mysql-cdc.md
> +  Download the latest source file of RisingWave. Run `./risedev configure` in the root directory of RisingWave and enable the **RisingWave Connector** component. Alternatively, you can edit the `rise
"**Alternatively, xxx**" This isn't an option, it is a required step to uncomment the line of code `- use: connector:node` to inform the `risedev` tool to launch the connector node.

2023-02-07 08:25 UTC, StrikeW commented on docs/guides/ingest-from-mysql-cdc.md
> +|database.name| Name of the database. Note that RisingWave cannot read data from a built-in MySQL database, such as `mysql`.|
such as `mysql` => such `mysql`, `sys`, etc.

2023-02-07 08:25 UTC, StrikeW commented on docs/guides/ingest-from-mysql-cdc.md
> +#### Create a materialized source using the Kafka connector in RisingWave
`materialized source` should change to `table`

2023-02-07 08:25 UTC, StrikeW commented on docs/guides/ingest-from-postgres-cdc.md
> +Here we will use a standard class instance without Multi-AZ deployment as an example.
This section belongs to `AWS RDS`, should not place in the `Set up PostgreSQL` section (see preview link).

2023-02-07 08:25 UTC, StrikeW commented on docs/guides/ingest-from-postgres-cdc.md
> +  Download the latest source file of RisingWave. Run `./risedev configure` in the root directory of RisingWave and enable the **RisingWave Connector** component. Alternatively, you can edit the `rise
ditto mysql guide

2023-02-08 07:09 UTC, CharlieSYH approved these changes

2023-02-08 22:35 UTC, emile-00 commented on docs/guides/ingest-from-postgres-cdc.md
> +Here we will use a standard class instance without Multi-AZ deployment as an example.
This section was likely rendered incorrectly. Please take a look again at the preview and let me know if it makes sense now!

2023-02-09 10:21 UTC, merged