Add dynamic filter container
risingwavelabs/risingwave-docs-legacy pull request #505
Opened 2023-01-20 19:53 UTC by bernscode

Add dynamic filter container.

## Info
- **Description**: 
Add dynamic filter container

- **Preview**: 
[ Paste the preview link to the edited page here. ]

- **Related code PR**: 
N/A

- **Related doc issue**: 
https://github.com/risingwavelabs/risingwave-docs/issues/493

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: <img width="916" alt="image" src="https://user-images.githubusercontent.com/100549427/199641563-82967cd0-2c5c-4f40-bcdb-5ac80f03ffd8.png">
</details>

2023-01-24 00:22 UTC, emile-00 approved these changes

2023-01-26 05:53 UTC, fuyufjh approved these changes

2023-01-26 05:55 UTC, fuyufjh commented
The content is basically copied from https://github.com/risingwavelabs/risingwave-docs/issues/493. Please feel free to add more descriptions so as to make it more understandable for users.

2023-01-29 08:19 UTC, hengm3467 commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +General non-equal joins are not supported in streaming, except for one special case. If a query with non-equal conditions meets the conditions below:
@bernscode This section is not easy to understand. What is the inner side? And we haven't introduced the concept of "streaming queries", so "not supported in streaming" will be confusing.

2023-01-29 08:35 UTC, hengm3467 commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +Then, dynamic filter will be adopted to run this streaming query:
The execution plan is unnecessary here. We can mention that as new data comes in, MAX(erase_ts) gets updated every now and then. When that happens, the data retrieved will change (some data will be trimmed).

2023-02-01 00:08 UTC, bernscode commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +General non-equal joins are not supported in streaming, except for one special case. If a query with non-equal conditions meets the conditions below:
@hengm3467 These are good points. I've added an intro to the concept of streaming queries. Thanks! What's a good way to describe what the doc refers to as the 'inner side' in this context?

2023-02-13 03:27 UTC, fuyufjh requested changes, later dismissed

2023-02-13 03:27 UTC, fuyufjh commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +Dynamic filter enables filtering data streams in real-time. It allows a condition to be defined that incoming data must meet in order to be processed. Therefore, it only captures the relevant data an
"Improving performance and reducing the amount of data stored" is not a motivation generally. In most cases the user just want the data of specified period, for example, "Please tell me the total selling amount in last 24 hours" - it's a user requirement rather than improving performance.

```suggestion
Dynamic filter enables filtering data streams in real-time. It allows a condition to be defined that incoming data must meet in order to be processed.
```

2023-02-13 03:27 UTC, fuyufjh commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +SELECT
May add the `CREATE MATERIALIZED VIEW` to avoid misunderstanding.

```suggestion
CREATE MATERIALIZED VIEW mv1 AS
SELECT
```

2023-02-13 03:27 UTC, fuyufjh commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +SELECT
FYI.
```
dev=> EXPLAIN CREATE MATERIALIZED VIEW mv1 AS
SELECT
  ps_partkey,
  sum(ps_supplycost * ps_availqty) AS value
FROM
  partsupp
GROUP BY
  ps_partkey
HAVING
  sum(ps_supplycost * ps_availqty) > (
    SELECT
      sum(ps_supplycost * ps_availqty) * 0.0001
    FROM
      partsupp
  );
                                                                                      QUERY PLAN
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 StreamMaterialize { columns: [ps_partkey, value], pk_columns: [ps_partkey] }
 └─StreamProject { exprs: [partsupp.ps_partkey, sum((partsupp.ps_supplycost * partsupp.ps_availqty))] }
   └─StreamDynamicFilter { predicate: (sum((partsupp.ps_supplycost * partsupp.ps_availqty)) > (sum(sum((partsupp.ps_supplycost * partsupp.ps_availqty))) * 0.0001:Decimal)) }
     ├─StreamProject { exprs: [partsupp.ps_partkey, sum((partsupp.ps_supplycost * partsupp.ps_availqty)), sum((partsupp.ps_supplycost * partsupp.ps_availqty))] }
     | └─StreamHashAgg { group_key: [partsupp.ps_partkey], aggs: [count, sum((partsupp.ps_supplycost * partsupp.ps_availqty)), sum((partsupp.ps_supplycost * partsupp.ps_availqty))] }
     |   └─StreamExchange { dist: HashShard(partsupp.ps_partkey) }
     |     └─StreamProject { exprs: [partsupp.ps_partkey, (partsupp.ps_supplycost * partsupp.ps_availqty), partsupp.ps_suppkey] }
     |       └─StreamTableScan { table: partsupp, columns: [ps_partkey, ps_availqty, ps_supplycost, ps_suppkey] }
     └─StreamExchange { dist: Broadcast }
       └─StreamProject { exprs: [(sum(sum((partsupp.ps_supplycost * partsupp.ps_availqty))) * 0.0001:Decimal)] }
         └─StreamGlobalSimpleAgg { aggs: [count, sum(sum((partsupp.ps_supplycost * partsupp.ps_availqty)))] }
           └─StreamExchange { dist: Single }
             └─StreamStatelessLocalSimpleAgg { aggs: [count, sum((partsupp.ps_supplycost * partsupp.ps_availqty))] }
               └─StreamProject { exprs: [(partsupp.ps_supplycost * partsupp.ps_availqty), partsupp.ps_partkey, partsupp.ps_suppkey] }
                 └─StreamTableScan { table: partsupp, columns: [ps_availqty, ps_supplycost, ps_partkey, ps_suppkey] }
(15 rows)
```

2023-02-13 03:27 UTC, fuyufjh commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +To add a dynamic filter to this query, we can change the hard-coded value of 0.0001 to a parameter called `threshold`. Now, the value of `threshold` can then be changed dynamically.
No that's wrong. Explained in our Slack talk.

```suggestion
```

2023-02-14 10:52 UTC, fuyufjh commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +
I think we can explain something about the concept of "dynamic filter" here, for example, show the reader the execution plan, and tell him what the dynamic filter does here. As a reader, I feel like I still don't understand the use of dynamic filter even after this example.

2023-02-14 17:57 UTC, bernscode commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +
@fuyufjh Okay, I can definitely add the execution plan. However, @hengm3467 did [previously mention that the execution plan (query plan) is unnecessary](https://github.com/risingwavelabs/risingwave-docs/pull/505#discussion_r1089899550). Could you please provide me with something we can add to explain what the dynamic filter does in this example? We can also remove this example, as the second example does explain the dynamic filter. Thanks!

2023-02-15 02:55 UTC, fuyufjh commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +
For this particular case, I recommend attaching the execution plan because the title "dynamic filter" is the name of the streaming operator, instead of a SQL syntax or a name of use cases. In other words, the reader can hardly understand the meaning of "dynamic filter" without seeing the execution plan.

2023-02-15 03:12 UTC, fuyufjh commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +
```suggestion
Under the hood, RisingWave maintains this materialized view with a continuous streaming job that filters the aggregation results according to the `HAVING` clause. Note that the result of the subquery (i.e., 0.01% of the total cost) is constantly changing, either increasing or decreasing depending on the incoming changes to the `partsupp` table.

Obviously, as this value increases, more results will satisfy this condition and be output; conversely, as this value decreases, more rows will be filtered out and fewer results will be output. RisingWave uses an internal stateful operator called Dynamic Filter to implement such a thing, which keeps a full set of results before filtering and decides which changes should be output according to both side - the original dataset (i.e. the outer side) and the filtering condition (i.e. the inner side).
```

2023-02-15 03:15 UTC, fuyufjh commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +
BTW, this paragraph seems verbose to me. How about leaving it out?

2023-02-15 21:12 UTC, bernscode commented on docs/sql/syntax/sql-pattern-dynamic-filter.md
> +
@fuyufjh Thanks for the input. Yes, I've remove that part and I've made the changes to the latest commit. Thanks!

2023-02-23 07:37 UTC, hengm3467 commented
@bernscode You may start to make the updates as we discussed earlier now. Then it's good to go from my side. Thanks.

2023-02-23 20:49 UTC, merged