Add RETURNING to INSERT and DELETE
risingwavelabs/risingwave-docs-legacy pull request #540
Opened 2023-02-03 20:33 UTC by bernscode

Add RETURNING to INSERT and DELETE

## Info
- **Description**: 
Add RETURNING to INSERT and DELETE.

- **Preview**: 
[ Paste the preview link to the edited page here. ]

- **Related code PR**: 
https://github.com/risingwavelabs/risingwave/pull/7094

- **Related doc issue**: 
Resolves https://github.com/risingwavelabs/risingwave-docs/issues/516

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: <img width="916" alt="image" src="https://user-images.githubusercontent.com/100549427/199641563-82967cd0-2c5c-4f40-bcdb-5ac80f03ffd8.png">
</details>

2023-02-03 20:36 UTC, Eurekaaw commented
LGTM, thanks!

2023-02-03 20:36 UTC, Eurekaaw approved these changes

2023-02-04 03:56 UTC, Eurekaaw requested changes
Apologies for the unclear information in my PR. Actually ```UPDATE``` should also be updated along with ```INSERT``` and ```DELETE``` (add ```RETURNING```).

2023-02-06 06:16 UTC, CharlieSYH approved these changes
Approved with two comments.

2023-02-06 06:16 UTC, CharlieSYH commented on docs/sql/commands/sql-delete.md
> +WHERE condition [ RETURNING col_name ];
In the syntax, please use a new line for RETURNING.
See this example: https://www.postgresql.org/docs/current/dml-returning.html

2023-02-06 06:16 UTC, CharlieSYH commented on docs/sql/commands/sql-insert.md
> +      { VALUES ( value [ , ... ] ) [ , ( ... ) ] | select_query } [ RETURNING col_name ];
Use a new line for RETURNING.

2023-02-06 19:42 UTC, bernscode commented on docs/sql/commands/sql-delete.md
> +WHERE condition [ RETURNING col_name ];
@CharlieSYH Good point! I've made the update to DELETE AND INSERT. Thanks!

2023-02-06 19:45 UTC, Eurekaaw approved these changes
LGTM

2023-02-07 00:34 UTC, merged