Add ascii() and support for multibyte Unicode
risingwavelabs/risingwave-docs-legacy pull request #849
Opened 2023-05-09 22:56 UTC by bernscode

Add ascii() and support for multibyte Unicode characters for ascii() and overlay().

## Info
- **Description**: 
Add ascii() and support for multibyte Unicode characters for ascii() and overlay().

- **Preview**: 
[ Paste the preview link to the edited page here. ]

- **Related code PR**: 
https://github.com/risingwavelabs/risingwave/pull/9321

- **Related doc issue**: 
Resolves https://github.com/risingwavelabs/risingwave-docs/issues/812

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: <img width="916" alt="image" src="https://user-images.githubusercontent.com/100549427/199641563-82967cd0-2c5c-4f40-bcdb-5ac80f03ffd8.png">
</details>

2023-05-10 03:09 UTC, xiangjinwu reviewed
All string functions are supposed to support multibyte Unicode characters. The PR just fixes the ones that fail to support them initially. We do not need to emphasize it per function. Maybe just add some examples to demonstrate the support?
`ascii('🌊')` → `127754`

2023-05-10 22:35 UTC, bernscode commented
@xiangjinwu Good point! I've made the update to the latest commit. Thanks for the feedback!

2023-05-11 00:28 UTC, xiangjinwu commented on docs/sql/functions-operators/sql-function-string.md
> +|overlay ( *input_string* PLACING *substring* FROM *start_int* [ FOR *length_int* ]) → *output_string* | Replaces a substring in *input_string* with *substring*, starting at *start_int* and with *len
`overlay('RisingWave' PLACING '🌊' FROM 7)` → `Rising🌊ave`

where the 🌊 is overlayed on the 7th character W

2023-05-11 00:39 UTC, xiangjinwu approved these changes

2023-05-11 00:42 UTC, bernscode commented on docs/sql/functions-operators/sql-function-string.md
> +|overlay ( *input_string* PLACING *substring* FROM *start_int* [ FOR *length_int* ]) → *output_string* | Replaces a substring in *input_string* with *substring*, starting at *start_int* and with *len
@xiangjinwu Thanks for catching that typo. I've made the update.

2023-05-11 07:15 UTC, hengm3467 approved these changes
LGTM

2023-05-16 02:45 UTC, xiangjinwu commented
Seems the `replace` function was lost during merge main

2023-05-16 09:17 UTC, CharlieSYH approved these changes

2023-05-16 09:23 UTC, CharlieSYH requested changes

2023-05-16 09:23 UTC, CharlieSYH commented on docs/sql/functions-operators/sql-function-string.md
> +|overlay ( *input_string* PLACING *substring* FROM *start_int* [ FOR *length_int* ]) → *output_string* | Replaces a substring in *input_string* with *substring*, starting at *start_int* and with *len
```suggestion
|`overlay` ( *input_string* PLACING *substring* FROM *start_int* [ FOR *length_int* ]) → *output_string* | Replaces a substring in *input_string* with *substring*, starting at *start_int* and with *length_int*. If *length_int* is omitted, its value is the length of *substring*. | `overlay('yabadoo' PLACING 'daba' FROM 5 FOR 0)` → `yabadabadoo` <br /> `overlay('abcdef' PLACING '45' FROM 4)` → `abc45f` <br /> `overlay('RisingWave' PLACING '🌊' FROM 7)` → `Rising🌊ave` |
```

2023-05-16 09:23 UTC, CharlieSYH commented on docs/sql/functions-operators/sql-function-string.md
> +| ascii( *input_string* ) → *int* | Returns the Unicode code point of the first character of the *input_string*. If the string is empty, it returns `NULL`. | `ascii('RisingWave')` → `82` <br /> `asci
```suggestion
| `ascii`( *input_string* ) → *int* | Returns the Unicode code point of the first character of the *input_string*. If the string is empty, it returns `NULL`. | `ascii('RisingWave')` → `82` <br /> `ascii('🌊')` → `127754` |
```

2023-05-16 09:23 UTC, CharlieSYH commented on docs/sql/functions-operators/sql-function-string.md
> +| ascii( *input_string* ) → *int* | Returns the Unicode code point of the first character of the *input_string*. If the string is empty, it returns `NULL`. | `ascii('RisingWave')` → `82` <br /> `asci
I tested using the code format for function names on this page. RN the function names are hard to identify when you browse through function pages. Let's add the `` for function names on this page.

2023-05-16 09:23 UTC, CharlieSYH commented on docs/sql/functions-operators/sql-function-string.md
> -|`replace` ( *input_string*, *from_string*, *to_string* ) → *output_string*|Replaces all occurrences of substring *from_string* in *input_string* with substring *to_string*.|`replace('abcdefabcdef',
Please restore the `replace` function. It should not be deleted.

2023-05-16 22:40 UTC, bernscode commented on docs/sql/functions-operators/sql-function-string.md
> -|`replace` ( *input_string*, *from_string*, *to_string* ) → *output_string*|Replaces all occurrences of substring *from_string* in *input_string* with substring *to_string*.|`replace('abcdefabcdef',
@CharlieSYH Thanks for pointing this out. I've re-added the `replace` function on the latest commit.

2023-05-17 02:36 UTC, CharlieSYH approved these changes

2023-05-19 08:12 UTC, merged