Add diagram for CREATE INDEX
risingwavelabs/risingwave-docs-legacy pull request #868
Opened 2023-05-12 22:00 UTC by bernscode

Add diagram for CREATE INDEX.

## Info
- **Description**: 
Add diagram for CREATE INDEX.

- **Preview**: 
[ Paste the preview link to the edited page here. ]

- **Related code PR**: 
N/A

- **Related doc issue**: 
Resolves no doc issue.

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: <img width="916" alt="image" src="https://user-images.githubusercontent.com/100549427/199641563-82967cd0-2c5c-4f40-bcdb-5ac80f03ffd8.png">
</details>

2023-05-17 03:16 UTC, CharlieSYH requested changes, later dismissed

2023-05-17 03:16 UTC, CharlieSYH commented on docs/sql/commands/sql-create-index.md
> +                rr.OneOrMore(
The comma separator is "something that must go between the repetitions". So it should be something like:

```
rr.OneOrMore(
 rr.NonTerminal('include_column'),
 rr.Terminal(',')
)
```

<img width="340" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/100549427/56c94bb9-a256-468c-a360-4d7a6c6a9de3">

<img width="955" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/100549427/d56117fa-a1a8-45dd-b3c8-d48d33f46b16">

2023-05-17 03:16 UTC, CharlieSYH commented on docs/sql/commands/sql-create-index.md
> +                rr.OneOrMore(
Same here.

2023-05-17 03:41 UTC, bernscode commented on docs/sql/commands/sql-create-index.md
> +                rr.OneOrMore(
@CharlieSYH I believe you're referring to the way I set up CREATE VIEW. Yes, that is the original way we had set it up. I was experimenting with other options. But, I believe this may work best. I've made the update. Thanks!

2023-06-05 11:50 UTC, hengm3467 approved these changes
LGTM. Thanks.

2023-06-07 22:52 UTC, merged