Document 256-bit integer type `rw_int256`
risingwavelabs/risingwave-docs-legacy pull request #876
Opened 2023-05-16 05:53 UTC by CharlieSYH

## Info

- **Preview**: 
[ Paste the preview link to the edited page here. ]

- **Related code PR**: 
https://github.com/risingwavelabs/risingwave/pull/9146
https://github.com/risingwavelabs/risingwave/pull/9184
https://github.com/risingwavelabs/risingwave/pull/9186
https://github.com/risingwavelabs/risingwave/pull/9191
https://github.com/risingwavelabs/risingwave/pull/9217

- **Related doc issue**: 
Resolves https://github.com/risingwavelabs/risingwave-docs/issues/804

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: <img width="916" alt="image" src="https://user-images.githubusercontent.com/100549427/199641563-82967cd0-2c5c-4f40-bcdb-5ac80f03ffd8.png">
</details>

2023-05-16 07:00 UTC, shanicky requested changes

2023-05-16 07:00 UTC, shanicky commented on docs/sql/data-types/data-type-rw_int256.md
> +Note that the input string must start with "0x" or "-0x". This function is not case-sensitive.
After the [pull request](https://github.com/risingwavelabs/risingwave/pull/9184), we no longer support expressions such as '-0xff'. The symbol is now encoded in hexadecimal format.

2023-05-17 03:27 UTC, shanicky approved these changes
LGTM

2023-05-17 04:12 UTC, hengm3467 approved these changes
Looks good. Thanks for the solid work. @CharlieSYH

2023-05-17 04:16 UTC, merged