Add Amazon MSK guide
risingwavelabs/risingwave-docs-legacy pull request #903
Opened 2023-05-24 19:35 UTC by bernscode

Add Amazon MSK guide.

## Info
- **Description**: 
Add Amazon MSK guide.

- **Preview**: 
[ Paste the preview link to the edited page here. Edit this item after you submit the PR and the preview is ready. ]

- **Related code PR**: 
N/A

- **Related doc issue**: 
Resolves no doc issue.

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: <img width="916" alt="image" src="https://user-images.githubusercontent.com/100549427/199641563-82967cd0-2c5c-4f40-bcdb-5ac80f03ffd8.png">
</details>

2023-05-30 21:58 UTC, emile-00 commented on docs/guides/connector-amazon-msk.md
> +create materialized source s (v1 int, v2 varchar) with (
Remember to use the conventional capitalization format for this SQL query.

2023-05-30 22:20 UTC, bernscode commented on docs/guides/connector-amazon-msk.md
> +create materialized source s (v1 int, v2 varchar) with (
@emile-00 Good catch! I've made the update on the latest commit. Thanks!

2023-05-30 23:20 UTC, emile-00 approved these changes

2023-05-31 01:07 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +This guide will detail the ingesting streaming data from Amazon MSK into RisingWave, enabling powerful and real-time data analytics in your workflows.
powerful and real-time data analytics sounds like marketing or sales language. Let's stick to point and focus on the purpose and procedures.

2023-05-31 01:14 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +1. Get the **VPC** value from the **All cluster settings** before clicking **Create cluster**.
I'm confused. The paragraph above step 1 says once you have created a cluster, and then we ask people note down something "before" clicking Create cluster. Is this possible?

2023-05-31 01:15 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +2. Get the **Security groups associated with VPC** from the **All cluster settings** before clicking **Create cluster**.
Same here. We probably want to separate what is needed before clicking Create cluster and after.

2023-05-31 01:16 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +3. Get the **ARN** value from the **Cluster summary** after clicking on **Create cluster**.
Clicking not clicking on.

2023-05-31 01:17 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +3. Click the **SASL/SCRAM authentication** checkbox and click **Save changes**.
click ... checkbox -> Select ...

2023-05-31 01:25 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +3. Run the following command using the `<broker-url>`.
The purpose of this step is to create a topic. I think we need to call it out. "using the <broker-url> is self-explanatory and therefore can be left out.

2023-05-31 01:25 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +6. Open another console and consume the message.
Is this step necessary?

2023-05-31 01:28 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +### Download Kafka workload from GitHub and write to Kafka
this step is unnecessary for external users. For internal users testing the product, we may need this. For external users, the step for producing messages is done in MSK. We are mixing things up here.

2023-05-31 01:28 UTC, hengm3467 requested changes
@bernscode Please see my comments and update the draft accordingly.

2023-06-05 06:46 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +4. Under **Administrative permissions**, select the **AWSServiceRoleForKafka** checkbox and click **Next**.
Just "Select **AWS...**..." would be good. Please do a global search in this topic so that it's consistent.

2023-06-05 23:40 UTC, bernscode commented
@hengm3467 I've made the updates that we discussed including the ones recently noted. Thanks!

2023-06-07 08:54 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +1. Run the following command.
Always mention the purpose in an action that you want users to take. In this case, the purpose is to configure AWS credentials and default settings

2023-06-07 08:55 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +3. Run the following command.
Again, please find out the purpose of this action.

2023-06-07 08:59 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +3. Run the following command.
Same here. The purpose is to create a topic, and step 5 is to insert data into the topic. Therefore, step 5 can be right after this step. And step 4 is totally optional.

2023-06-07 09:01 UTC, hengm3467 commented on docs/guides/connector-amazon-msk.md
> +5. Insert test data.
Info I found: 

"Once you run the kafka-console-producer command, you will be prompted to enter messages into the console. Each message should be entered on a new line, and you can enter as many messages as you like.

When you are finished entering messages, you can simply close the console window or press Ctrl + C to exit the producer."

2023-06-07 22:25 UTC, bernscode commented
@hengm3467 I've made the suggested changes to the latest commit. Thanks!

2023-06-09 01:21 UTC, hengm3467 approved these changes
LGTM. Thanks.

2023-06-09 01:21 UTC, merged