Document SHOW CREATE INDEX command
risingwavelabs/risingwave-docs-legacy pull request #913
Opened 2023-05-26 23:59 UTC by emile-00

## Info
- **Description**: 
Document SHOW CREATE INDEX command

- **Preview**: 
[ Paste the preview link to the edited page here. Edit this item after you submit the PR and the preview is ready. ]

- **Related code PR**: 
https://github.com/risingwavelabs/risingwave/pull/9839

- **Related doc issue**: 
Resolves https://github.com/risingwavelabs/risingwave-docs/issues/884

- **Notes**: 
[ Any additional information? ]

## Before merging
  - [ ] (For version-specific PR) I have selected the corresponding software version in **Milestone** and linked the related doc issue to this PR in **Development**.
  - [ ] I have acquired the approval from the owner (and optionally the reviewers) of the code PR and at least one tech writer (`bernscode`, `CharlieSYH`, `emile-00`, & `hengm3467`). 
  - [ ] I have checked the doc site preview, and the updated parts look good. <details><summary>How?</summary>Scroll down and open this link: <img width="916" alt="image" src="https://user-images.githubusercontent.com/100549427/199641563-82967cd0-2c5c-4f40-bcdb-5ac80f03ffd8.png">
</details>

2023-05-28 15:24 UTC, chenzl25 requested changes
Append only is an experimental feature, so I think we should not use it in the example.

2023-05-28 15:24 UTC, chenzl25 commented on docs/sql/commands/sql-show-create-index.md
> +CREATE TABLE IS NOT EXISTS t3 (
```suggestion
CREATE TABLE IF NOT EXISTS t3 (
```

2023-05-28 15:24 UTC, chenzl25 commented on docs/sql/commands/sql-show-create-index.md
> +    v3 int) append only;
```suggestion
    v3 int);
```

2023-05-29 14:37 UTC, CharlieSYH approved these changes
Else LGTM

2023-05-29 14:37 UTC, CharlieSYH commented on docs/sql/commands/sql-show-create-index.md
> +[CREATE INDEX](/sql-create-index.md)
```suggestion
[CREATE INDEX](sql-create-index.md)
```

2023-06-05 11:44 UTC, hengm3467 approved these changes

2023-06-06 03:49 UTC, chenzl25 approved these changes

2023-06-06 20:15 UTC, merged